import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/def.module.css';
import mystyles from '../styles/cus.module.css';
import Script from 'next/script'
import Link from 'next/link'
//  Components
import Navbar from '../src/components/Navbar'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Basic Funda Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script></Script> */}
      <Navbar>

      </Navbar>
      <main className={styles.main}>
        <h1 className={styles.title}>
         Basic Funda developer
        </h1>

        <p className={styles.description}>
        For coders, By a coder
          
        </p>

       <div className={mystyles.blogs}>
           <h2>Popular Blogs</h2>
         <div className={mystyles.blogItem}>
           <h3>How to learn Javascript 2022</h3>
           <p>Javascript is used to add logic to websites</p>
         </div>
         <div className={mystyles.blogItem}>
           <h3>How to learn Javascript 2022</h3>
           <p>Javascript is used to add logic to websites</p>
         </div>
         <div className={mystyles.blogItem}>
           <h3>How to learn Javascript 2022</h3>
           <p>Javascript is used to add logic to websites</p>
         </div>
         <div className="bg-red-700"> hello</div>
       </div>
      </main>

    </div>
  )
}
