import Head from 'next/head'
import styles from '../styles/def.module.css';
import Script from 'next/script'
import Link from 'next/link'
//  Components
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Basic Funda Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script id="my-id" strategy="beforeInteractive" src="https://cdn.tailwindcss.com"> </Script>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Basic Funda developer
        </h1>

        <p className="text-center font-bold text-violet-400 m-4">
          For coders, By a coder
        </p>

       <div>
         <div className="bg-lime-200 text-lime-600 font-mono text-lg font-bold p-5">Click on 'Blogs' to see the blogs</div>
       </div>
      </main>

    </div>
  )
}
