import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Basic Funda Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script></Script> */}
      <nav className={styles.navigation}>
        <ul>
          <Link href="/"><a><li>Home</li></a></Link>
          <Link href="/blogs"><a><li>Blogs</li></a></Link>
          <Link href="/contact"><a><li>Contact</li></a></Link>
          <Link href="/about"><a><li>About</li></a></Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
         Basic Funda developer
        </h1>

        <p className={styles.description}>
        For coders, By a coder
          
        </p>

       <div className="blogs">
           <h2>Popular Blogs</h2>
         <div className="blog-item">
           <h3>How to learn Javascript 2022</h3>
           <p>Javascript is used to add logic to websites</p>
         </div>
         <div className="blog-item">
           <h3>How to learn Javascript 2022</h3>
           <p>Javascript is used to add logic to websites</p>
         </div>
         
         <div className="blog-item">
           <h3>How to learn Javascript 2022</h3>
           <p>Javascript is used to add logic to websites</p>
         </div>
         
       </div>
      </main>

    </div>
  )
}
